source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.3'
use_frameworks!
#inhibit_all_warnings!

def socialFeedPods
    pod 'AFNetworking', '~> 3.0'
    pod "HanekeSwift", :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
end

target 'Social Feed' do
    socialFeedPods
end

target 'Social FeedTests' do
    socialFeedPods
end
