source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.3'
#use_frameworks!
#inhibit_all_warnings!

def socialFeedPods
    pod 'InstagramKit', '~> 3.0'
    pod 'InstagramKit/UICKeyChainStore'
end

target 'Social Feed' do
    socialFeedPods
end

target 'Social FeedTests' do
    socialFeedPods
end
